name: Push Helm Chart
description: 'Push helm chart via OCI'
inputs:
  name:
    required: true
    description: Helm chart name
  path:
    required: true
    description: Path to the helm chart
  version:
    description: Version of the helm chart to set. If unspecifed, uses version in Chart.yaml.
  values_file_changes:
    description: |
      Use this to patch the values.yaml before pushing the chart.
      Expected format: {"propertyPath":"value", "propertyPath2":"value2"}
  registry:
    description: "OCI registry to push to. Eg: 'quay.io'"
    required: true
  registry_namespace:
    required: true
    description: 'Remote helm namespace/org. For example in quay.io/cilium-charts/cilium, cilium-charts is the namespace.'
  registry_username:
    description: "OCI registry username"
    required: true
  registry_password:
    description: "OCI registry password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure helm repositories
      shell: bash
      env:
        REGISTRY_NAME: ${{ inputs.registry }}
        REGISTRY_USERNAME: ${{ inputs.registry_username }}
        REGISTRY_PASSWORD: ${{ inputs.registry_password }}
      run: |
        helm registry login "$REGISTRY_NAME" -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
    - name: Update helm chart values.yaml
      if: ${{ inputs.values_file_changes }}
      uses: mikefarah/yq@751d8ad57b84f1794661bc70c0afb92a22ad7b3c # v4.53.2
      env:
        HELM_PATH: ${{ inputs.path }}
        VALUES_FILE_CHANGES: ${{ inputs.values_file_changes }}
      with:
        cmd: |
          echo "$VALUES_FILE_CHANGES" > values-file-changes.json
          yq -i '. as $input | load("values-file-changes.json") | to_entries | .[] as $item ireduce ($input; setpath(($item.key | split("."); $item.value)))' "$HELM_PATH/values.yaml"
    - name: Push helm chart
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        HELM_PATH: ${{ inputs.path }}
        HELM_NAME: ${{ inputs.name }}
        REGISTRY_NAME: ${{ inputs.registry }}
        REGISTRY_NAMESPACE: ${{ inputs.registry_namespace }}
      run: |
        if [[ -z "$VERSION" ]]; then
          helm package --dependency-update "$HELM_PATH"
        else
          helm package --dependency-update "$HELM_PATH" --version "$VERSION" --app-version "$VERSION"
        fi
        helm push "$HELM_NAME"-*.tgz "oci://$REGISTRY_NAME/$REGISTRY_NAMESPACE"
